### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by tulsiqt** [tulsiqt/otstudy#4]
Many questions about what version to release otstudy as. Perhaps when I implement the JavaScript/J Query, then I can release version 1.0, and maybe when I add the database and user registration page to this project I can release version 1.1, or 2.1. 

Which brings me to: how do I know what version to use? I read the info on the semantics of the version number, need help putting everything into perspective.

**Comment by Natasha08** [comment]
The healthdb will be receiving a version first. This may be published as a static site.
